### ISSUE TITLE
Error on Node-Red 3.1.0

### ISSUE THREAD

**Issue by delike** [DaveMDS/node-red-contrib-tasmota#51]
The SensorNode thows the following Error on each MQTT-Message:

Error: 
    at Object.evaluateJSONataExpression (/usr/lib/node_modules/node-red/node_modules/@node-red/util/lib/util.js:775:18)
    at TasmotaSensorNode.sendToOutputs (/root/.node-red/node_modules/node-red-contrib-tasmota/nodes/sensor.js:50:35)
    at TasmotaSensorNode.onSensorTelemetry (/root/.node-red/node_modules/node-red-contrib-tasmota/nodes/sensor.js:60:14)
    at /root/.node-red/node_modules/node-red-contrib-tasmota/nodes/sensor.js:16:14
    at MqttClient.<anonymous> (/root/.node-red/node_modules/node-red-contrib-tasmota/nodes/mqtt_broker.js:113:21)
    at MqttClient.emit (events.js:400:28)
    at MqttClient._handlePublish (/root/.node-red/node_modules/mqtt/lib/client.js:1277:12)
    at MqttClient._handlePacket (/root/.node-red/node_modules/mqtt/lib/client.js:410:12)
    at work (/root/.node-red/node_modules/mqtt/lib/client.js:321:12)
    at Writable.writable._write (/root/.node-red/node_modules/mqtt/lib/client.js:335:5)
    at doWrite (/root/.node-red/node_modules/mqtt/node_mod...

**Comment by DaveMDS** [comment]
Duplicate of #49

Please search in open issue's before posting a new one
